services:
  backend1:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 5m
    image: polarlightning/bitcoind:27.0
    container_name: polar-n1-backend1
    hostname: backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
      -blockfilterindex=1 -peerblockfilters=1
    volumes:
      - ./testsetup.polar/volumes/bitcoind/backend1:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18445:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
    networks:
      - nostr-dice-network
  alice:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    depends_on:
      - backend1
    stop_grace_period: 2m
    image: polarlightning/lnd:0.18.2-beta
    container_name: alice
    hostname: alice
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=alice --externalip=alice
      --tlsextradomain=alice
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
    restart: always
    volumes:
      - ./testsetup.polar/volumes/lnd/alice:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8082:8080'
      - '10001:10009'
      - '9735:9735'
    networks:
      - nostr-dice-network
  bob:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    depends_on:
      - backend1
    stop_grace_period: 2m
    image: polarlightning/lnd:0.18.2-beta
    container_name: bob
    hostname: bob
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=bob --externalip=bob
      --tlsextradomain=bob
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
    restart: always
    volumes:
      - ./testsetup.polar/volumes/lnd/bob:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8083:8080'
      - '10002:10009'
      - '9736:9735'
    networks:
      - nostr-dice-network

  nostrdice:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: nostrdice
    depends_on:
      - nostr-rs-relay
      - alice
      - bob
    volumes:
      - ./data/:/data
      - ./testsetup.polar/volumes/lnd/bob/tls.cert:/config/tls.cert
      - ./testsetup.polar/volumes/lnd/bob/data/chain/bitcoin/regtest/admin.macaroon:/config/admin.macaroon
      - ./config/cert.pem/:/usr/local/share/ca-certificates/nginx-proxy.crt
    command:
      - --relay=ws://nostr-rs-relay:8080
      - --data-dir=/data
      - --domain=localhost
      - --port=1993
      - --lnd-host=bob
      - --lnd-port=10009
      - --network=regtest
      - --cert-file=/config/tls.cert
      - --macaroon-file=/config/admin.macaroon
      - --multipliers-file=/data/multipliers.yml
      - --expire-nonce-after-secs=30
      - --reveal-nonce-after-secs=30
    networks:
      - nostr-dice-network
    environment:
      - DATABASE_URL=sqlite:/data/zaps.db?mode=rwc

  nostr-rs-relay:
    image: ghcr.io/luckysori/nostr-rs-relay/nostr-rs-relay
    container_name: nostr-rs-relay
    networks:
      - nostr-dice-network
    ports:
      - "7000:8080"

  nostr-wallet-connect-lnd:
    image: ghcr.io/benthecarman/nostr-wallet-connect-lnd:master
    container_name: nostr-wallet-connect-lnd
    networks:
      - nostr-dice-network
    volumes:
      - ./config/nwc-lnd-keys.json:/config/keys.json
      - ./testsetup.polar/volumes/lnd/alice/tls.cert:/config/tls.cert
      - ./testsetup.polar/volumes/lnd/alice/data/chain/bitcoin/regtest/admin.macaroon:/config/admin.macaroon
    working_dir: /app
    environment:
      - RUST_LOG=DEBUG
    command:
      - ./nostr-wallet-connect-lnd
      - --keys-file=/config/keys.json
      - --relay=ws://nostr-rs-relay:8080
      - --lnd-host=alice
      - --lnd-port=10009
      - --cert-file=/config/tls.cert
      - --macaroon-file=/config/admin.macaroon
    depends_on:
      - nostr-rs-relay
      - alice
      - bob
    restart: always

  webserver:
    image: nginx:latest
    container_name: webserver
    hostname: webserver
    depends_on:
      - nostrdice
    networks:
      - nostr-dice-network
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./config/:/etc/nginx/conf.d/:ro
      - ./config/:/var/www/cert/:ro

  roller-lnurl-server:
    image: ghcr.io/luckysori/lnurl-server:latest
    container_name: roller-lnurl-server
    command:
      - --relay=ws://nostr-rs-relay:8080
      - --data-dir=/data
      - --domain=roller-lnurl-server-proxy
      - --port=1993
      - --lnd-host=alice
      - --lnd-port=10009
      - --network=regtest
      - --cert-file=/config/tls.cert
      - --macaroon-file=/config/admin.macaroon
    depends_on:
      - nostr-rs-relay
      - alice
      - bob
    volumes:
      - ./data-roller-lnurl-server/:/data
      - ./testsetup.polar/volumes/lnd/alice/tls.cert:/config/tls.cert
      - ./testsetup.polar/volumes/lnd/alice/data/chain/bitcoin/regtest/admin.macaroon:/config/admin.macaroon
    networks:
      - nostr-dice-network
    restart: always

  roller-lnurl-server-proxy:
    image: nginx:latest
    container_name: roller-lnurl-server-proxy
    hostname: roller-lnurl-server-proxy
    depends_on:
      - roller-lnurl-server
    networks:
      - nostr-dice-network
    restart: always
    volumes:
      - ./config/roller-lnurl-server-proxy/:/etc/nginx/conf.d/:ro
      - ./config/:/var/www/cert/:ro

networks:
  nostr-dice-network:
